export const FUNCTION_DB = "com.axelor.apps.base.db.Function"
export const USER_DB = "com.axelor.auth.db.User"
export const LEAD_DB = "com.axelor.apps.crm.db.Lead"
export const TEAM_DB = "com.axelor.team.db.Team"
export const SOURCE_DB = "com.axelor.apps.base.db.Source"
export const CITY_DB = "com.axelor.apps.base.db.City"
export const COUNTRY_DB = "com.axelor.apps.base.db.Country"
export const REGION_DB = "com.axelor.apps.base.db.Region"
